// scripts/build-tokens.mjs — design-tokens/*.json → _tokens.generated.scss
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'

const root = join(import.meta.dirname, '..')
const SRC = join(root, 'design-tokens')
const OUT = join(root, 'src/scss/abstracts/_tokens.generated.scss')

const collections = readdirSync(SRC)
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(readFileSync(join(SRC, f), 'utf8')))

function scssName(collection, name) {
  const full = name.toLowerCase().startsWith(`${collection.toLowerCase()}/`)
    ? name
    : `${collection}/${name}`
  return `$${full.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')}`
}

// id → 變數名，跨集合解析 alias 用
const idToVar = new Map()
for (const c of collections)
  for (const v of c.variables ?? []) idToVar.set(v.id, scssName(c.name, v.name))

function pickModeValue(c, v) {
  const lightId = Object.entries(c.modes ?? {}).find(([, n]) => n === 'Light')?.[0]
  return v.valuesByMode[lightId] ?? Object.values(v.valuesByMode)[0]
}

const hex = (n) => Math.round(n * 255).toString(16).padStart(2, '0')

function format(value, collectionName, varName) {
  if (value && typeof value === 'object' && 'r' in value) {
    const { r, g, b, a } = value
    if (a === 1) return `#${hex(r)}${hex(g)}${hex(b)}`
    return `rgba(${Math.round(r * 255)}, ${Math.round(g * 255)}, ${Math.round(b * 255)}, ${+a.toFixed(3)})`
  }
  if (typeof value === 'number')
    return collectionName === 'Font' && /weight/i.test(varName) ? `${value}` : `${value}px`
  if (typeof value === 'string') return `"${value}"`
  return `${value}`
}

const plain = []
const aliasEntries = [] // { name, target } —— 之後依相依關係排序輸出
for (const c of collections) {
  for (const v of c.variables ?? []) {
    const value = pickModeValue(c, v)
    const name = scssName(c.name, v.name)
    if (value && typeof value === 'object' && value.type === 'VARIABLE_ALIAS') {
      const target = idToVar.get(value.id)
      if (target) aliasEntries.push({ name, target })
      else console.warn(`略過無法解析的 alias：${name} → ${value.id}`)
    } else {
      plain.push(`${name}: ${format(value, c.name, v.name)};`)
    }
  }
}

// alias 拓樸排序：被其他 alias 引用者排前面，避免 alias→alias 的前向引用造成 Undefined variable
const aliasNames = new Set(aliasEntries.map((a) => a.name))
const emitted = new Set()
const aliases = []
let progressed = true
while (aliasEntries.length > emitted.size && progressed) {
  progressed = false
  for (const a of aliasEntries) {
    if (emitted.has(a.name)) continue
    // 目標若是另一個尚未輸出的 alias，先跳過
    if (aliasNames.has(a.target) && !emitted.has(a.target)) continue
    aliases.push(`${a.name}: ${a.target};`)
    emitted.add(a.name)
    progressed = true
  }
}
// 殘餘（循環引用，理論上不會發生）按原序補上
for (const a of aliasEntries)
  if (!emitted.has(a.name)) aliases.push(`${a.name}: ${a.target};`)

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(
  OUT,
  ['// AUTO-GENERATED by scripts/build-tokens.mjs — 勿手改；token 更新後執行 npm run tokens', ...plain, ...aliases, ''].join('\n'),
)
console.log(`已寫入 ${plain.length} 個變數 + ${aliases.length} 個 alias → src/scss/abstracts/_tokens.generated.scss`)
